### ISSUE TITLE
Why +1 to padding?

### ISSUE THREAD

**Issue by yhahn** [mapbox/maki-chef#17]
@samanpwbb could you explain this `+1` ?

https://github.com/mapbox/maki-chef/blob/mb-pages/src/icon.js#L62

I'm seeing that this adds an additional 1px of space to the dimensions of the exported SVG that leads to some pixel misalignment when rendered.

**Comment by samanpwbb** [comment]
I think this is left over from an earlier attempt at getting the padding right. Shouldn't be there.

**Comment by yhahn** [comment]
Rad :rice: :bow:
