### ISSUE TITLE
Stroke width doubles on output from set value

### ISSUE THREAD

**Issue by amyleew** [mapbox/maki-chef#20]
A stroke set as `2px` in UI results in `4px` stroke svg.

![image](https://cloud.githubusercontent.com/assets/4587826/13090041/957e384a-d4c1-11e5-930c-f4f4f2d4fc34.png)

![image](https://cloud.githubusercontent.com/assets/4587826/13090060/aac7f772-d4c1-11e5-965d-3e7b212a9244.png)

/cc @samanpwbb

**Comment by samanpwbb** [comment]
Not a bug. SVG strokes are applied to the center of path, so a stroke width of 4 gives you 2pxs of outer stroke.

**Comment by amyleew** [comment]
Maybe good to note in the UI, could cause confusion IMHO.
